### ISSUE TITLE
Language Model Question

### ISSUE THREAD

**Issue by BinWang28** [yunsukim86/wbw-lm#1]
Hi Yunsu,

Thanks for your excellent work. I am trying to repeat your result in the paper. I have a question about the Language Model.

For training with kelnm, what corpus is used? Same with the corpus used in monolingual word embedding?

Thanks so much!

**Comment by yunsukim86** [comment]
Hi Bin,

yes, we did use the same data for learning word embedding and language model: 100M sentences
sampled from News Crawl 2014-2017 monolingual corpora.

Best regards,
Yunsu

**Comment by BinWang28** [comment]
Many thank!
